name=NINA
version=0.1.0
author=Angel
maintainer=Angel
sentence=Cliente ESP32 para conectarse al servidor local NINA.
paragraph=Permite escuchar variables del servidor Flask mediante WebSocket y reaccionar con callbacks simples.
category=Communication
url=
architectures=esp32
depends=ArduinoJson,WebSockets
